#!/usr/bin/env bash

failed=""

make test || exit 1
for binary in ./debug/*; do
	if [ -f $binary ]; then
		echo "===> $(basename $binary)"
		$binary || failed="$failed$(basename $binary) "
	fi
done

if [ -n "$failed" ]; then
	echo >&2
	echo -e "\033[0;31mfailed tests: $failed\033[0m" >&2
	exit 1
fi
