#!/usr/bin/env bash

failed=""

make test || exit 1
for binary in ./debug/*; do
	if [ -f $binary ]; then
		echo "===> $(basename $binary)"
		$binary || failed="$failed$(basename $binary) "
	fi
done

if [ -n "$failed" ]; then
	echo >&2
	echo -e "\033[0;31mfailed tests: $failed\033[0m" >&2
fi

if fd '^ft_[^\.]+\.c$' -X norminette | grep -E '^(Error|Warning)' 2>&1 >/dev/null; then
	echo >&2
	echo -e "\033[0;31mnorm failed:\033[0m" >&2
	fd '^ft_[^\.]+\.c$' -X norminette
fi
