#!/bin/sh
if [ $# -eq 1 ]; then
	echo "please run 'meson test -v norm' from the build directory"
	echo "(or run 'meson test -v' for all tests)"
fi
cd "$(dirname "$0")/.." || exit 1
! norminette "$@" src/**/*.h 2>/dev/null | tee /dev/stderr | grep -q Error
