#!/bin/sh
# mkmod - create the boilerplate files for a new module.
#
# Running `./scripts/mkmod foo` will create the `src/foo/foo.h` and
# `src/foo/meson.build` files.

if [ $# -ne 1 ]; then
	echo "Usage: $0 <modname>"
	exit 1
fi

modname="$1"
moddir="$(dirname "$0")/../src/$modname"
if [ -d "$moddir" ]; then
	echo "module $modname already exists"
	exit 1
fi

mkdir "$moddir"
cat > "$moddir/meson.build" <<EOF
src_files += files()

test_files += files()
EOF

uppercase_modname=$(echo "$modname" | tr '[:lower:]' '[:upper:]')
guard_name="$uppercase_modname"_H

cat > "$moddir/$modname.h" <<EOF
/* ************************************************************************** */
/*                                                                            */
/*   tosh - 21 Shell                                      ::::::::            */
/*                                                      :+:    :+:            */
/*   By: aholster <aholster@student.codam.nl>          +:+                    */
/*       ivan-tey <ivan-tey@student.codam.nl>         +#+                     */
/*       nloomans <nloomans@student.codam.nl>        +#+                      */
/*                                                 #+#    #+#                 */
/*   License: GPLv3                                ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#ifndef $guard_name
# define $guard_name

#endif
EOF

echo "directory src/$modname created, be sure to add"
echo
echo "  subdir('src/$modname')"
echo
echo "to the root meson.build file"
