#!/bin/sh
# mkmod - create the boilerplate files for a new module.
#
# Running `./scripts/mkmod foo` will create the `src/foo/foo.h` and
# `src/foo/meson.build` files.

if [ $# -ne 1 ]; then
	echo "Usage: $0 <modname>"
	exit 1
fi

modname="$1"
moddir="$(dirname "$0")/../src/$modname"
if [ -d "$moddir" ]; then
	echo "module $modname already exists"
	exit 1
fi

mkdir "$moddir"
cat > "$moddir/meson.build" <<EOF
src_files += files()

test_files += files()
EOF

uppercase_modname=$(echo "$modname" | tr '[:lower:]' '[:upper:]')
guard_name="$uppercase_modname"_H

cat > "$moddir/$modname.h" <<EOF
/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   Tosh-21Shell                                       :+:    :+:            */
/*                                                     +:+                    */
/*   By: tosh <tosh@student.codam.nl>                 +#+                     */
/*                                                   +#+                      */
/*   Created: 1970/01/01 00:00:00 by tosh          #+#    #+#                 */
/*   Updated: 1970/01/01 99:99:99 by tosh          ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#ifndef $guard_name
# define $guard_name

#endif
EOF

echo "directory src/$modname created, be sure to add"
echo
echo "  subdir('src/$modname')"
echo
echo "to the root meson.build file"
